apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: expense
  labels:
    project: expense
data:
  DB_HOST: expense-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      project: expense
      tier: backend
      env: dev
  template:
    metadata:
      name: backend
      labels:
        project: expense
        tier: backend
        env: dev
    spec:
      containers:
      - name: backend
        image: amarnadh31/backend:v2
        envFrom:
        - configMapRef:
            name: backend-config
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
  labels:
    project: expense
    tier: backend
spec:
  selector:
    project: expense
    tier: backend
    env: dev
  ports:
  - name: backend-ports
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-demo-deployment
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: backend
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 15