apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: expense
data:
  primary.cnf: |
    [mysqld]
    server-id=1
    log-bin=mysql-bin
    binlog-do-db=transactions
    enforce-gtid-consistency=true
    gtid-mode=ON
    log-slave-updates=true
    replicate-same-server-id=0
  replica.cnf: |
    [mysqld]
    server-id={{ .pod.index }}
    relay-log=mysql-relay-bin
    log-bin=mysql-bin
    read-only=1
  template.cnf: |
    [mysqld]
    server-id = ${SERVER_ID}
  my_custom.cnf: |
    [mysqld]
    !include /etc/my_custom_conf.d/*.cnf
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  serviceName: mysql
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:
      - name: init-config
        image: busybox
        command:
          - sh
          - -c
          - |
            echo "Creating directory /etc/my_custom_conf.d"
            mkdir -p /etc/my_custom_conf.d
            echo "Substituting SERVER_ID..."
            envsubst < /etc/mysql/template.cnf > /etc/my_custom_conf.d/custom.cnf
            cat /etc/my_custom_conf.d/custom.cnf  # Debugging step to check if substitution works
        env:
          - name: SERVER_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
              - name: config-volume
                mountPath: /etc/mysql  # Mount the configMap to /etc/mysql
              - name: custom-config-volume
                mountPath: /etc/my_custom_conf.d
      containers:
        - name: mysql
          image: mysql:8.0
          volumeMounts:
            - name: config-volume
              mountPath: /etc/mysql/conf.d
              subPath: custom.cnf
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "Amarapp@1"
      volumes:
      - name: config-volume
        configMap:
          name: mysql-config
          items:
            - key: template.cnf
              path: template.cnf
      - name: custom-config-volume
        emptyDir: {} 
  volumeClaimTemplates:
      - metadata:
          name: mysql-pvc
          namespace: expense
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: "ebs-sc"
          resources:
            requests:
              storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: expense
spec:
  ports:
  - port: 3306
    targetPort: 3306
  clusterIP: None
  selector:
    app: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: expense-mysql
  namespace: expense
spec:
  selector:
    app: mysql
  ports:
  - name: mysql-port
    protocol: TCP
    port: 3306
    targetPort: 3306