apiVersion: v1
kind: Service
metadata:
  name: expense-headless
  namespace: expense
  labels:
    project: expense
    tier: db
    env: dev
spec:
  clusterIP: None
  selector:
    project: expense
    tier: db
    env: dev
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
  labels:
    project: expense
    env: dev
spec:
  selector:
    project: expense
    tier: db
    env: dev
  ports:
  - name: mysql-port
    protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-stateful
  namespace: expense
spec:
  replicas: 2
  serviceName: "expense-headless"
  selector:
    matchLabels:
      project: expense
      tier: db
      env: dev
  template:
    metadata:
      labels:
        project: expense
        tier: db
        env: dev
    spec:
      containers:
      - name: mysql
        image: amarnadh31/mysql:v1
        volumeMounts:
        - name: mysql-pvc
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-pvc
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 5Gi
